apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app
  namespace: mi-app
  labels:
    app: mi-app
    pipecd.dev/variant: primary   # <-- Obligatorio para que PipeCD gestione variantes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: mi-app
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: ngnix
        image: nginx:alpine
        ports:
        - containerPort: 80
