apiVersion: v1
data:
  piped-config.yaml: |-
    apiVersion: pipecd.dev/v1beta1
    kind: Piped
    spec:
      projectID: quickstart
      pipedID: 1776f9b8-e037-43ee-b79a-d0540e9937f1
      pipedKeyData: YjNkanZqZ2g3NGkxeGw3Ymw5MWxvN2pvYzN5NjNraG96ZWJhMWw4cDJuOTNsNTBvcGY=
      apiAddress: pipecd:8080
      syncInterval: 1m
      repositories:
        - repoId: pipecd-demo
          remote: https://github.com/CarlosAlejo/pipecd-demo.git
          branch: main
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"piped-config.yaml":"apiVersion: pipecd.dev/v1beta1\nkind: Piped\nspec:\n  projectID: quickstart\n  pipedID: 1776f9b8-e037-43ee-b79a-d0540e9937f1\n  pipedKeyData: YjNkanZqZ2g3NGkxeGw3Ymw5MWxvN2pvYzN5NjNraG96ZWJhMWw4cDJuOTNsNTBvcGY=\n  apiAddress: pipecd:8080\n  syncInterval: 1m\n  repositories:\n    - repoId: examples\n      remote: https://github.com/pipe-cd/examples.git\n      branch: master"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"piped","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"piped","app.kubernetes.io/version":"v0.56.0","helm.sh/chart":"piped-v0.56.0"},"name":"piped","namespace":"pipecd"}}
  creationTimestamp: "2026-08-06T17:54:54Z"
  labels:
    app.kubernetes.io/instance: piped
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: piped
    app.kubernetes.io/version: v0.56.0
    helm.sh/chart: piped-v0.56.0
  name: piped
  namespace: pipecd
  resourceVersion: "19900"
  uid: 7f63ca5d-f900-4153-8e03-d8c45bcbcc8b
