apiVersion: v1
kind: Service
metadata:
  name: mi-app
  namespace: mi-app
spec:
  selector:
    app: mi-app   # <-- Sin la variante, para que enrute tanto a primary como a canary
  ports:
  - port: 80
    targetPort: 9085
